// Code generated by Slice Machine. DO NOT EDIT.

import AudienceOverview from './AudienceOverview/index.svelte';
import CtaBlock from './CtaBlock/index.svelte';
import FaqGroup from './FaqGroup/index.svelte';
import FeatureCardsGrid from './FeatureCardsGrid/index.svelte';
import FeatureScreenshot from './FeatureScreenshot/index.svelte';
import FeatureSideHero from './FeatureSideHero/index.svelte';
import FeatureVideo from './FeatureVideo/index.svelte';
import FeatureWIthImage from './FeatureWIthImage/index.svelte';
import GradientCta from './GradientCta/index.svelte';
import HeadlineOverlay from './HeadlineOverlay/index.svelte';
import Hero from './Hero/index.svelte';
import HeroOverBackgroundImage from './HeroOverBackgroundImage/index.svelte';
import HeroWithScreenshot from './HeroWithScreenshot/index.svelte';
import ImageBlock from './ImageBlock/index.svelte';
import NewsletterSignUp from './NewsletterSignUp/index.svelte';
import PageTitle from './PageTitle/index.svelte';
import PricingComparisonTable from './PricingComparisonTable/index.svelte';
import PricingOverview from './PricingOverview/index.svelte';
import FeaturedBlogPosts from './FeaturedBlogPosts/index.svelte';
import RichText from './RichText/index.svelte';
import SectionWithSubsections from './SectionWithSubsections/index.svelte';
import SingleTestimonial from './SingleTestimonial/index.svelte';
import TeamOverview from './TeamOverview/index.svelte';
import TheWhy from './TheWhy/index.svelte';
import UseCase from './UseCase/index.svelte';
import VideoHero from './VideoHero/index.svelte';

export const components = {
	audience_overview: AudienceOverview,
	cta_block: CtaBlock,
	faq_group: FaqGroup,
	feature_cards_grid: FeatureCardsGrid,
	feature_screenshot: FeatureScreenshot,
	feature_side_hero: FeatureSideHero,
	feature_video: FeatureVideo,
	feature_w_ith_image: FeatureWIthImage,
	gradient_cta: GradientCta,
	headline_overlay: HeadlineOverlay,
	hero: Hero,
	hero_over_background_image: HeroOverBackgroundImage,
	hero_with_screenshot: HeroWithScreenshot,
	image_block: ImageBlock,
	newsletter_sign_up: NewsletterSignUp,
	page_title: PageTitle,
	pricing_comparison_table: PricingComparisonTable,
	pricing_overview: PricingOverview,
	recent_blog_posts: FeaturedBlogPosts,
	rich_text: RichText,
	section_with_subsections: SectionWithSubsections,
	single_testimonial: SingleTestimonial,
	team_overview: TeamOverview,
	the_why: TheWhy,
	use_case: UseCase,
	video_hero: VideoHero
};
