// Code generated by Slice Machine. DO NOT EDIT.

import AudienceOverview from './AudienceOverview/index.svelte';
import FaqGroup from './FaqGroup/index.svelte';
import FeatureCardsGrid from './FeatureCardsGrid/index.svelte';
import FeatureScreenshot from './FeatureScreenshot/index.svelte';
import FeatureSideHero from './FeatureSideHero/index.svelte';
import FeatureWIthImage from './FeatureWIthImage/index.svelte';
import FooterNavigation from './FooterNavigation/index.svelte';
import HeadlineOverlay from './HeadlineOverlay/index.svelte';
import Hero from './Hero/index.svelte';
import ImageBlock from './ImageBlock/index.svelte';
import PageTitle from './PageTitle/index.svelte';
import PlanComparisonTable from './PlanComparisonTable/index.svelte';
import FeaturedBlogPosts from './FeaturedBlogPosts/index.svelte';
import RichText from './RichText/index.svelte';
import SectionWithSubsections from './SectionWithSubsections/index.svelte';
import TeamOverview from './TeamOverview/index.svelte';

export const components = {
	audience_overview: AudienceOverview,
	faq_group: FaqGroup,
	feature_cards_grid: FeatureCardsGrid,
	feature_screenshot: FeatureScreenshot,
	feature_side_hero: FeatureSideHero,
	feature_w_ith_image: FeatureWIthImage,
	footer_navigation: FooterNavigation,
	headline_overlay: HeadlineOverlay,
	hero: Hero,
	image_block: ImageBlock,
	page_title: PageTitle,
	plan_comparison_table: PlanComparisonTable,
	recent_blog_posts: FeaturedBlogPosts,
	rich_text: RichText,
	section_with_subsections: SectionWithSubsections,
	team_overview: TeamOverview
};
