// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
	>,
	TLang extends string
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>;
	} & // Group
	{
		[TGroup in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
			? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
			: never;
	} & // Other fields
	{
		[TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
			? TData[TFieldKey]
			: never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>;
}[Exclude<TCustomType[number], string>['id']];

type BlogPostDocumentDataSlicesSlice = RichTextSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
	/**
	 * Featured Image field in *Blog Post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.cover_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cover_image: prismic.ImageField<never>;

	/**
	 * Title field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;

	/**
	 * Publish Date field in *Blog Post*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.publish_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	publish_date: prismic.DateField;

	/**
	 * Label field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * Slice Zone field in *Blog Post*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
	 * Meta Title field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: blog_post.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: blog_post.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Blog Post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<BlogPostDocumentData>,
	'blog_post',
	Lang
>;

type FooterDocumentDataSlicesSlice = FooterNavigationSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * Slice Zone field in *Footer*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<FooterDocumentData>,
	'footer',
	Lang
>;

type HomepageDocumentDataSlicesSlice =
	| FeatureScreenshotSlice
	| HeroSlice
	| FeatureSideHeroSlice
	| FeatureCardsGridSlice
	| FaqGroupSlice
	| AudienceOverviewSlice;

/**
 * Content for Home Page documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Home Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Home Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Home Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Home Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HomepageDocumentData>,
	'homepage',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| RecentBlogPostsSlice
	| PageTitleSlice
	| RichTextSlice
	| ImageBlockSlice
	| FaqGroupSlice
	| FeatureSideHeroSlice
	| HeadlineOverlaySlice
	| TeamOverviewSlice
	| SectionWithSubsectionsSlice
	| FeatureCardsGridSlice
	| AudienceOverviewSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = BlogPostDocument | FooterDocument | HomepageDocument | PageDocument;

/**
 * Item in *AudienceOverview → Standard → Primary → Audience Types*
 */
export interface AudienceOverviewSliceStandardPrimaryAudienceTypesItem {
	/**
	 * Icon field in *AudienceOverview → Standard → Primary → Audience Types*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: audience_overview.standard.primary.audience_types[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>;

	/**
	 * Audience Label field in *AudienceOverview → Standard → Primary → Audience Types*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: audience_overview.standard.primary.audience_types[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * Audience Description field in *AudienceOverview → Standard → Primary → Audience Types*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: audience_overview.standard.primary.audience_types[].audience_description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	audience_description: prismic.RichTextField;
}

/**
 * Primary content in *AudienceOverview → Standard → Primary*
 */
export interface AudienceOverviewSliceStandardPrimary {
	/**
	 * Section Label field in *AudienceOverview → Standard → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: audience_overview.standard.primary.preheading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	preheading: prismic.KeyTextField;

	/**
	 * Section Title field in *AudienceOverview → Standard → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: audience_overview.standard.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;

	/**
	 * Description field in *AudienceOverview → Standard → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: audience_overview.standard.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Audience Types field in *AudienceOverview → Standard → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: audience_overview.standard.primary.audience_types[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	audience_types: prismic.GroupField<
		Simplify<AudienceOverviewSliceStandardPrimaryAudienceTypesItem>
	>;
}

/**
 * Standard variation for AudienceOverview Slice
 *
 * - **API ID**: `standard`
 * - **Description**: Includes a pre-heading, main heading, supporting text, and a repeatable group for multiple audience types with icon, label, and description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AudienceOverviewSliceStandard = prismic.SharedSliceVariation<
	'standard',
	Simplify<AudienceOverviewSliceStandardPrimary>,
	never
>;

/**
 * Slice variation for *AudienceOverview*
 */
type AudienceOverviewSliceVariation = AudienceOverviewSliceStandard;

/**
 * AudienceOverview Shared Slice
 *
 * - **API ID**: `audience_overview`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AudienceOverviewSlice = prismic.SharedSlice<
	'audience_overview',
	AudienceOverviewSliceVariation
>;

/**
 * Item in *FaqGroup → Default → Primary → FAQs*
 */
export interface FaqGroupSliceDefaultPrimaryFaqsItem {
	/**
	 * Question field in *FaqGroup → Default → Primary → FAQs*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_group.default.primary.faqs[].question
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	question: prismic.RichTextField;

	/**
	 * Answer field in *FaqGroup → Default → Primary → FAQs*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_group.default.primary.faqs[].answer
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	answer: prismic.RichTextField;
}

/**
 * Primary content in *FaqGroup → Default → Primary*
 */
export interface FaqGroupSliceDefaultPrimary {
	/**
	 * Title field in *FaqGroup → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_group.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Introduction field in *FaqGroup → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_group.default.primary.intro
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	intro: prismic.RichTextField;

	/**
	 * FAQs field in *FaqGroup → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: faq_group.default.primary.faqs[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	faqs: prismic.GroupField<Simplify<FaqGroupSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for FaqGroup Slice
 *
 * - **API ID**: `default`
 * - **Description**: FAQ list with introduction and questions/answers.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqGroupSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FaqGroupSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FaqGroup*
 */
type FaqGroupSliceVariation = FaqGroupSliceDefault;

/**
 * FaqGroup Shared Slice
 *
 * - **API ID**: `faq_group`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqGroupSlice = prismic.SharedSlice<'faq_group', FaqGroupSliceVariation>;

/**
 * Item in *FeatureCardsGrid → Default → Primary → Features*
 */
export interface FeatureCardsGridSliceDefaultPrimaryFeaturesItem {
	/**
	 * Illustration field in *FeatureCardsGrid → Default → Primary → Features*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_cards_grid.default.primary.features[].illustration
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	illustration: prismic.ImageField<never>;

	/**
	 * Feature Title field in *FeatureCardsGrid → Default → Primary → Features*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_cards_grid.default.primary.features[].feature_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	feature_title: prismic.KeyTextField;

	/**
	 * Feature Description field in *FeatureCardsGrid → Default → Primary → Features*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_cards_grid.default.primary.features[].feature_description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	feature_description: prismic.RichTextField;
}

/**
 * Primary content in *FeatureCardsGrid → Default → Primary*
 */
export interface FeatureCardsGridSliceDefaultPrimary {
	/**
	 * Section Label field in *FeatureCardsGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_cards_grid.default.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * Title field in *FeatureCardsGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_cards_grid.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *FeatureCardsGrid → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_cards_grid.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Features field in *FeatureCardsGrid → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_cards_grid.default.primary.features[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	features: prismic.GroupField<Simplify<FeatureCardsGridSliceDefaultPrimaryFeaturesItem>>;
}

/**
 * Default variation for FeatureCardsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout: heading, description, and a group of image/feature cards in a grid.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureCardsGridSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FeatureCardsGridSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FeatureCardsGrid*
 */
type FeatureCardsGridSliceVariation = FeatureCardsGridSliceDefault;

/**
 * FeatureCardsGrid Shared Slice
 *
 * - **API ID**: `feature_cards_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureCardsGridSlice = prismic.SharedSlice<
	'feature_cards_grid',
	FeatureCardsGridSliceVariation
>;

/**
 * Primary content in *FeatureScreenshot → Default → Primary*
 */
export interface FeatureScreenshotSliceDefaultPrimary {
	/**
	 * Section Label field in *FeatureScreenshot → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_screenshot.default.primary.section_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_label: prismic.KeyTextField;

	/**
	 * Title field in *FeatureScreenshot → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_screenshot.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Screenshot field in *FeatureScreenshot → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_screenshot.default.primary.screenshot
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	screenshot: prismic.ImageField<never>;
}

/**
 * Default variation for FeatureScreenshot Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureScreenshotSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FeatureScreenshotSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *FeatureScreenshot → Dark → Primary*
 */
export interface FeatureScreenshotSliceDarkPrimary {
	/**
	 * Section Label field in *FeatureScreenshot → Dark → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_screenshot.dark.primary.section_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_label: prismic.KeyTextField;

	/**
	 * Title field in *FeatureScreenshot → Dark → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_screenshot.dark.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Screenshot field in *FeatureScreenshot → Dark → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_screenshot.dark.primary.screenshot
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	screenshot: prismic.ImageField<never>;
}

/**
 * Dark variation for FeatureScreenshot Slice
 *
 * - **API ID**: `dark`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureScreenshotSliceDark = prismic.SharedSliceVariation<
	'dark',
	Simplify<FeatureScreenshotSliceDarkPrimary>,
	never
>;

/**
 * Slice variation for *FeatureScreenshot*
 */
type FeatureScreenshotSliceVariation = FeatureScreenshotSliceDefault | FeatureScreenshotSliceDark;

/**
 * FeatureScreenshot Shared Slice
 *
 * - **API ID**: `feature_screenshot`
 * - **Description**: FeatureScreenshot
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureScreenshotSlice = prismic.SharedSlice<
	'feature_screenshot',
	FeatureScreenshotSliceVariation
>;

/**
 * Item in *FeatureSideHero → With Icon Features → Primary → Features*
 */
export interface FeatureSideHeroSliceWithIconFeaturesPrimaryFeaturesItem {
	/**
	 * Icon field in *FeatureSideHero → With Icon Features → Primary → Features*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.with_icon_features.primary.features[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>;

	/**
	 * Feature Title field in *FeatureSideHero → With Icon Features → Primary → Features*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.with_icon_features.primary.features[].feature_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	feature_title: prismic.KeyTextField;

	/**
	 * Feature Description field in *FeatureSideHero → With Icon Features → Primary → Features*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.with_icon_features.primary.features[].feature_desc
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	feature_desc: prismic.RichTextField;
}

/**
 * Item in *FeatureSideHero → Left Image → Primary → Features*
 */
export interface FeatureSideHeroSliceLeftImagePrimaryFeaturesItem {
	/**
	 * Icon field in *FeatureSideHero → Left Image → Primary → Features*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.leftImage.primary.features[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>;

	/**
	 * Feature Title field in *FeatureSideHero → Left Image → Primary → Features*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.leftImage.primary.features[].feature_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	feature_title: prismic.KeyTextField;

	/**
	 * Feature Description field in *FeatureSideHero → Left Image → Primary → Features*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.leftImage.primary.features[].feature_desc
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	feature_desc: prismic.RichTextField;
}

/**
 * Primary content in *FeatureSideHero → With Icon Features → Primary*
 */
export interface FeatureSideHeroSliceWithIconFeaturesPrimary {
	/**
	 * Section Label field in *FeatureSideHero → With Icon Features → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.with_icon_features.primary.section_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_label: prismic.KeyTextField;

	/**
	 * Section Title field in *FeatureSideHero → With Icon Features → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.with_icon_features.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;

	/**
	 * Description field in *FeatureSideHero → With Icon Features → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.with_icon_features.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Features field in *FeatureSideHero → With Icon Features → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.with_icon_features.primary.features[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	features: prismic.GroupField<Simplify<FeatureSideHeroSliceWithIconFeaturesPrimaryFeaturesItem>>;

	/**
	 * Side Image field in *FeatureSideHero → With Icon Features → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.with_icon_features.primary.side_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	side_image: prismic.ImageField<never>;
}

/**
 * With Icon Features variation for FeatureSideHero Slice
 *
 * - **API ID**: `with_icon_features`
 * - **Description**: Displays a headline, descriptive text, a list of features each with an icon and optional description, along with a main image/app screenshot on the right.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSideHeroSliceWithIconFeatures = prismic.SharedSliceVariation<
	'with_icon_features',
	Simplify<FeatureSideHeroSliceWithIconFeaturesPrimary>,
	never
>;

/**
 * Primary content in *FeatureSideHero → Left Image → Primary*
 */
export interface FeatureSideHeroSliceLeftImagePrimary {
	/**
	 * Section Label field in *FeatureSideHero → Left Image → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.leftImage.primary.section_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_label: prismic.KeyTextField;

	/**
	 * Section Title field in *FeatureSideHero → Left Image → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.leftImage.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField;

	/**
	 * Description field in *FeatureSideHero → Left Image → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.leftImage.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Features field in *FeatureSideHero → Left Image → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.leftImage.primary.features[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	features: prismic.GroupField<Simplify<FeatureSideHeroSliceLeftImagePrimaryFeaturesItem>>;

	/**
	 * Side Image field in *FeatureSideHero → Left Image → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_side_hero.leftImage.primary.side_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	side_image: prismic.ImageField<never>;
}

/**
 * Left Image variation for FeatureSideHero Slice
 *
 * - **API ID**: `leftImage`
 * - **Description**: Displays a headline, descriptive text, a list of features each with an icon and optional description, along with a main image/app screenshot on the right.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSideHeroSliceLeftImage = prismic.SharedSliceVariation<
	'leftImage',
	Simplify<FeatureSideHeroSliceLeftImagePrimary>,
	never
>;

/**
 * Slice variation for *FeatureSideHero*
 */
type FeatureSideHeroSliceVariation =
	| FeatureSideHeroSliceWithIconFeatures
	| FeatureSideHeroSliceLeftImage;

/**
 * FeatureSideHero Shared Slice
 *
 * - **API ID**: `feature_side_hero`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSideHeroSlice = prismic.SharedSlice<
	'feature_side_hero',
	FeatureSideHeroSliceVariation
>;

/**
 * Item in *FeatureWIthImage → Default → Primary → Features*
 */
export interface FeatureWIthImageSliceDefaultPrimaryFeaturesItem {
	/**
	 * Icon field in *FeatureWIthImage → Default → Primary → Features*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_w_ith_image.default.primary.features[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>;

	/**
	 * Feature Title field in *FeatureWIthImage → Default → Primary → Features*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_w_ith_image.default.primary.features[].feature_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	feature_title: prismic.KeyTextField;

	/**
	 * Feature Description field in *FeatureWIthImage → Default → Primary → Features*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_w_ith_image.default.primary.features[].feature_desc
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	feature_desc: prismic.RichTextField;
}

/**
 * Primary content in *FeatureWIthImage → Default → Primary*
 */
export interface FeatureWIthImageSliceDefaultPrimary {
	/**
	 * Tag field in *FeatureWIthImage → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_w_ith_image.default.primary.tag
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tag: prismic.KeyTextField;

	/**
	 * Title field in *FeatureWIthImage → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_w_ith_image.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *FeatureWIthImage → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_w_ith_image.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Image field in *FeatureWIthImage → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_w_ith_image.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Features field in *FeatureWIthImage → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_w_ith_image.default.primary.features[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	features: prismic.GroupField<Simplify<FeatureWIthImageSliceDefaultPrimaryFeaturesItem>>;
}

/**
 * Default variation for FeatureWIthImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureWIthImageSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FeatureWIthImageSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FeatureWIthImage*
 */
type FeatureWIthImageSliceVariation = FeatureWIthImageSliceDefault;

/**
 * FeatureWIthImage Shared Slice
 *
 * - **API ID**: `feature_w_ith_image`
 * - **Description**: FeatureWIthImage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureWIthImageSlice = prismic.SharedSlice<
	'feature_w_ith_image',
	FeatureWIthImageSliceVariation
>;

/**
 * Item in *FooterNavigation → Default → Primary → Social Links*
 */
export interface FooterNavigationSliceDefaultPrimarySocialLinksItem {
	/**
	 * Icon field in *FooterNavigation → Default → Primary → Social Links*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_navigation.default.primary.social_links[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>;

	/**
	 * URL field in *FooterNavigation → Default → Primary → Social Links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_navigation.default.primary.social_links[].url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *FooterNavigation → Default → Primary → Navigation Columns*
 */
export interface FooterNavigationSliceDefaultPrimaryNavigationColumnsItem {
	/**
	 * Column Title field in *FooterNavigation → Default → Primary → Navigation Columns*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_navigation.default.primary.navigation_columns[].column_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	column_title: prismic.KeyTextField;

	/**
	 * Links field in *FooterNavigation → Default → Primary → Navigation Columns*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_navigation.default.primary.navigation_columns[].links
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	links: prismic.Repeatable<prismic.LinkField<string, string, unknown, prismic.FieldState, never>>;
}

/**
 * Primary content in *FooterNavigation → Default → Primary*
 */
export interface FooterNavigationSliceDefaultPrimary {
	/**
	 * Description field in *FooterNavigation → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_navigation.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Social Links field in *FooterNavigation → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_navigation.default.primary.social_links[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	social_links: prismic.GroupField<Simplify<FooterNavigationSliceDefaultPrimarySocialLinksItem>>;

	/**
	 * Navigation Columns field in *FooterNavigation → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer_navigation.default.primary.navigation_columns[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	navigation_columns: prismic.GroupField<
		Simplify<FooterNavigationSliceDefaultPrimaryNavigationColumnsItem>
	>;
}

/**
 * Default variation for FooterNavigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Base footer structure with branding, grouped navigation links, description, social icons, and disclaimer.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterNavigationSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FooterNavigationSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FooterNavigation*
 */
type FooterNavigationSliceVariation = FooterNavigationSliceDefault;

/**
 * FooterNavigation Shared Slice
 *
 * - **API ID**: `footer_navigation`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterNavigationSlice = prismic.SharedSlice<
	'footer_navigation',
	FooterNavigationSliceVariation
>;

/**
 * Primary content in *HeadlineOverlay → Default → Primary*
 */
export interface HeadlineOverlaySliceDefaultPrimary {
	/**
	 * Background Image field in *HeadlineOverlay → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: headline_overlay.default.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * Title field in *HeadlineOverlay → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: headline_overlay.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *HeadlineOverlay → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: headline_overlay.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for HeadlineOverlay Slice
 *
 * - **API ID**: `default`
 * - **Description**: Primary variation with a headline, description, and image.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadlineOverlaySliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeadlineOverlaySliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HeadlineOverlay*
 */
type HeadlineOverlaySliceVariation = HeadlineOverlaySliceDefault;

/**
 * HeadlineOverlay Shared Slice
 *
 * - **API ID**: `headline_overlay`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadlineOverlaySlice = prismic.SharedSlice<
	'headline_overlay',
	HeadlineOverlaySliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Hero Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.hero_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	hero_image: prismic.ImageField<never>;

	/**
	 * Hero Text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.hero_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	hero_text: prismic.KeyTextField;

	/**
	 * Hero Subtext field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.hero_subtext
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	hero_subtext: prismic.KeyTextField;

	/**
	 * Primary Click field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.primary_click
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	primary_click: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *ImageBlock → Default → Primary*
 */
export interface ImageBlockSliceDefaultPrimary {
	/**
	 * Image field in *ImageBlock → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_block.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageBlockSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageBlockSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ImageBlock*
 */
type ImageBlockSliceVariation = ImageBlockSliceDefault;

/**
 * ImageBlock Shared Slice
 *
 * - **API ID**: `image_block`
 * - **Description**: ImageBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageBlockSlice = prismic.SharedSlice<'image_block', ImageBlockSliceVariation>;

/**
 * Primary content in *PageTitle → Default → Primary*
 */
export interface PageTitleSliceDefaultPrimary {
	/**
	 * Title field in *PageTitle → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_title.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Label field in *PageTitle → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_title.default.primary.section_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_label: prismic.KeyTextField;

	/**
	 * Description field in *PageTitle → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page_title.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for PageTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageTitleSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PageTitleSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *PageTitle*
 */
type PageTitleSliceVariation = PageTitleSliceDefault;

/**
 * PageTitle Shared Slice
 *
 * - **API ID**: `page_title`
 * - **Description**: PageTitle
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageTitleSlice = prismic.SharedSlice<'page_title', PageTitleSliceVariation>;

/**
 * Item in *PlanComparisonTable → Default → Primary → Plans*
 */
export interface PlanComparisonTableSliceDefaultPrimaryPlansItem {
	/**
	 * Plan Label field in *PlanComparisonTable → Default → Primary → Plans*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: plan_comparison_table.default.primary.plans[].plan_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	plan_label: prismic.KeyTextField;

	/**
	 * Call to Action field in *PlanComparisonTable → Default → Primary → Plans*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: plan_comparison_table.default.primary.plans[].cta
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *PlanComparisonTable → Default → Primary → Features*
 */
export interface PlanComparisonTableSliceDefaultPrimaryFeaturesItem {
	/**
	 * Feature Label field in *PlanComparisonTable → Default → Primary → Features*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: plan_comparison_table.default.primary.features[].feature_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	feature_label: prismic.KeyTextField;

	/**
	 * Plan 1 Value field in *PlanComparisonTable → Default → Primary → Features*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: plan_comparison_table.default.primary.features[].plan_1_value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	plan_1_value: prismic.KeyTextField;

	/**
	 * Plan 2 Value field in *PlanComparisonTable → Default → Primary → Features*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: plan_comparison_table.default.primary.features[].plan_2_value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	plan_2_value: prismic.KeyTextField;

	/**
	 * Plan 3 Value field in *PlanComparisonTable → Default → Primary → Features*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: plan_comparison_table.default.primary.features[].plan_3_value
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	plan_3_value: prismic.KeyTextField;
}

/**
 * Primary content in *PlanComparisonTable → Default → Primary*
 */
export interface PlanComparisonTableSliceDefaultPrimary {
	/**
	 * Plans field in *PlanComparisonTable → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: plan_comparison_table.default.primary.plans[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	plans: prismic.GroupField<Simplify<PlanComparisonTableSliceDefaultPrimaryPlansItem>>;

	/**
	 * Features field in *PlanComparisonTable → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: plan_comparison_table.default.primary.features[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	features: prismic.GroupField<Simplify<PlanComparisonTableSliceDefaultPrimaryFeaturesItem>>;
}

/**
 * Default variation for PlanComparisonTable Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard comparison table layout for different plans with corresponding features and plan actions.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PlanComparisonTableSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PlanComparisonTableSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *PlanComparisonTable*
 */
type PlanComparisonTableSliceVariation = PlanComparisonTableSliceDefault;

/**
 * PlanComparisonTable Shared Slice
 *
 * - **API ID**: `plan_comparison_table`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PlanComparisonTableSlice = prismic.SharedSlice<
	'plan_comparison_table',
	PlanComparisonTableSliceVariation
>;

/**
 * Item in *FeaturedBlogPosts → Default → Primary → featured_posts*
 */
export interface RecentBlogPostsSliceDefaultPrimaryFeaturedPostsItem {
	/**
	 * featured_post field in *FeaturedBlogPosts → Default → Primary → featured_posts*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent_blog_posts.default.primary.featured_posts[].featured_post
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	featured_post: ContentRelationshipFieldWithData<
		[{ id: 'blog_post'; fields: ['cover_image', 'title', 'description', 'publish_date', 'label'] }]
	>;
}

/**
 * Primary content in *FeaturedBlogPosts → Default → Primary*
 */
export interface RecentBlogPostsSliceDefaultPrimary {
	/**
	 * Title field in *FeaturedBlogPosts → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent_blog_posts.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *FeaturedBlogPosts → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent_blog_posts.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * featured_posts field in *FeaturedBlogPosts → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: recent_blog_posts.default.primary.featured_posts[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	featured_posts: prismic.GroupField<Simplify<RecentBlogPostsSliceDefaultPrimaryFeaturedPostsItem>>;
}

/**
 * Default variation for FeaturedBlogPosts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RecentBlogPostsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RecentBlogPostsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FeaturedBlogPosts*
 */
type RecentBlogPostsSliceVariation = RecentBlogPostsSliceDefault;

/**
 * FeaturedBlogPosts Shared Slice
 *
 * - **API ID**: `recent_blog_posts`
 * - **Description**: RecentBlogPosts
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RecentBlogPostsSlice = prismic.SharedSlice<
	'recent_blog_posts',
	RecentBlogPostsSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Item in *SectionWithSubsections → Default → Primary → Subsections*
 */
export interface SectionWithSubsectionsSliceDefaultPrimarySubsectionsItem {
	/**
	 * Subsection Heading field in *SectionWithSubsections → Default → Primary → Subsections*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: section_with_subsections.default.primary.subsections[].subsection_heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subsection_heading: prismic.KeyTextField;

	/**
	 * Subsection Content field in *SectionWithSubsections → Default → Primary → Subsections*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: section_with_subsections.default.primary.subsections[].content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Primary content in *SectionWithSubsections → Default → Primary*
 */
export interface SectionWithSubsectionsSliceDefaultPrimary {
	/**
	 * Subsections field in *SectionWithSubsections → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: section_with_subsections.default.primary.subsections[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	subsections: prismic.GroupField<
		Simplify<SectionWithSubsectionsSliceDefaultPrimarySubsectionsItem>
	>;
}

/**
 * Default variation for SectionWithSubsections Slice
 *
 * - **API ID**: `default`
 * - **Description**: Section with a main title and a repeatable group for as many subsections as needed. Each subsection has a heading and description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionWithSubsectionsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SectionWithSubsectionsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *SectionWithSubsections*
 */
type SectionWithSubsectionsSliceVariation = SectionWithSubsectionsSliceDefault;

/**
 * SectionWithSubsections Shared Slice
 *
 * - **API ID**: `section_with_subsections`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionWithSubsectionsSlice = prismic.SharedSlice<
	'section_with_subsections',
	SectionWithSubsectionsSliceVariation
>;

/**
 * Item in *TeamOverview → Default → Primary → Members*
 */
export interface TeamOverviewSliceDefaultPrimaryMembersItem {
	/**
	 * Avatar field in *TeamOverview → Default → Primary → Members*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_overview.default.primary.members[].avatar
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	avatar: prismic.ImageField<never>;

	/**
	 * Name field in *TeamOverview → Default → Primary → Members*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_overview.default.primary.members[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;

	/**
	 * Role field in *TeamOverview → Default → Primary → Members*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_overview.default.primary.members[].role
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	role: prismic.KeyTextField;
}

/**
 * Primary content in *TeamOverview → Default → Primary*
 */
export interface TeamOverviewSliceDefaultPrimary {
	/**
	 * Title field in *TeamOverview → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_overview.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *TeamOverview → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_overview.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;

	/**
	 * Members field in *TeamOverview → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_overview.default.primary.members[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	members: prismic.GroupField<Simplify<TeamOverviewSliceDefaultPrimaryMembersItem>>;
}

/**
 * Default variation for TeamOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard team overview showing heading, description, and team members.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamOverviewSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TeamOverviewSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TeamOverview*
 */
type TeamOverviewSliceVariation = TeamOverviewSliceDefault;

/**
 * TeamOverview Shared Slice
 *
 * - **API ID**: `team_overview`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamOverviewSlice = prismic.SharedSlice<'team_overview', TeamOverviewSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			BlogPostDocument,
			BlogPostDocumentData,
			BlogPostDocumentDataSlicesSlice,
			FooterDocument,
			FooterDocumentData,
			FooterDocumentDataSlicesSlice,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			AudienceOverviewSlice,
			AudienceOverviewSliceStandardPrimaryAudienceTypesItem,
			AudienceOverviewSliceStandardPrimary,
			AudienceOverviewSliceVariation,
			AudienceOverviewSliceStandard,
			FaqGroupSlice,
			FaqGroupSliceDefaultPrimaryFaqsItem,
			FaqGroupSliceDefaultPrimary,
			FaqGroupSliceVariation,
			FaqGroupSliceDefault,
			FeatureCardsGridSlice,
			FeatureCardsGridSliceDefaultPrimaryFeaturesItem,
			FeatureCardsGridSliceDefaultPrimary,
			FeatureCardsGridSliceVariation,
			FeatureCardsGridSliceDefault,
			FeatureScreenshotSlice,
			FeatureScreenshotSliceDefaultPrimary,
			FeatureScreenshotSliceDarkPrimary,
			FeatureScreenshotSliceVariation,
			FeatureScreenshotSliceDefault,
			FeatureScreenshotSliceDark,
			FeatureSideHeroSlice,
			FeatureSideHeroSliceWithIconFeaturesPrimaryFeaturesItem,
			FeatureSideHeroSliceWithIconFeaturesPrimary,
			FeatureSideHeroSliceLeftImagePrimaryFeaturesItem,
			FeatureSideHeroSliceLeftImagePrimary,
			FeatureSideHeroSliceVariation,
			FeatureSideHeroSliceWithIconFeatures,
			FeatureSideHeroSliceLeftImage,
			FeatureWIthImageSlice,
			FeatureWIthImageSliceDefaultPrimaryFeaturesItem,
			FeatureWIthImageSliceDefaultPrimary,
			FeatureWIthImageSliceVariation,
			FeatureWIthImageSliceDefault,
			FooterNavigationSlice,
			FooterNavigationSliceDefaultPrimarySocialLinksItem,
			FooterNavigationSliceDefaultPrimaryNavigationColumnsItem,
			FooterNavigationSliceDefaultPrimary,
			FooterNavigationSliceVariation,
			FooterNavigationSliceDefault,
			HeadlineOverlaySlice,
			HeadlineOverlaySliceDefaultPrimary,
			HeadlineOverlaySliceVariation,
			HeadlineOverlaySliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			ImageBlockSlice,
			ImageBlockSliceDefaultPrimary,
			ImageBlockSliceVariation,
			ImageBlockSliceDefault,
			PageTitleSlice,
			PageTitleSliceDefaultPrimary,
			PageTitleSliceVariation,
			PageTitleSliceDefault,
			PlanComparisonTableSlice,
			PlanComparisonTableSliceDefaultPrimaryPlansItem,
			PlanComparisonTableSliceDefaultPrimaryFeaturesItem,
			PlanComparisonTableSliceDefaultPrimary,
			PlanComparisonTableSliceVariation,
			PlanComparisonTableSliceDefault,
			RecentBlogPostsSlice,
			RecentBlogPostsSliceDefaultPrimaryFeaturedPostsItem,
			RecentBlogPostsSliceDefaultPrimary,
			RecentBlogPostsSliceVariation,
			RecentBlogPostsSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			SectionWithSubsectionsSlice,
			SectionWithSubsectionsSliceDefaultPrimarySubsectionsItem,
			SectionWithSubsectionsSliceDefaultPrimary,
			SectionWithSubsectionsSliceVariation,
			SectionWithSubsectionsSliceDefault,
			TeamOverviewSlice,
			TeamOverviewSliceDefaultPrimaryMembersItem,
			TeamOverviewSliceDefaultPrimary,
			TeamOverviewSliceVariation,
			TeamOverviewSliceDefault
		};
	}
}
